
kafka:
    producer-topic: "producer.topic"
    consumer-topic: "consumer.topic"
    messageKey: "si.key"
    group-id: "siTestGroup"
    auto-offset-reset: "earliest"
    enable-auto-commit: false
    #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    boostrap-servers: "192.168.99.147:9092"
    zookeeper-connect: "192.168.99.147:2181"

