# Set the REGISTRY_IP environment variable to override the registry IP

version: "3.7"

services:
  producer:
    image: ${REGISTRY_IP}/producer:latest
    depends_on:
      - kafka1

# Kafka:
  zookeeper:
    image: ${REGISTRY_IP}/zookeeper:latest
    volumes:
      - zoo-stack-data:/tmp/zookeeper
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: ${REGISTRY_IP}/kafka:latest
    volumes:
       - kafka-logs:/tmp/kafka-logs
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 9094:9094
        - target: 9092
          published: 9092
          protocol: tcp
          mode: host
    deploy:
        replicas: 3
    environment:
        ALLOW_PLAINTEXT_LISTENER: "yes"
        KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
        KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://{{.Node.Hostname}}:9094
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

volumes:
  kafka-logs:
  zoo-stack-data:

